-- Run after booking_reliability.sql in the SAME rollback transaction.
reset role;
select set_config('request.jwt.claim.sub', customer_a::text, true) from booking_test_context;
set local role authenticated;
select pg_temp.check_booking_test((get_my_privacy()->'preferences'->>'analytics')::boolean = false, 'Optional analytics defaults off');
select pg_temp.check_booking_test(next_customer_survey() is null, 'Survey defaults off');
select record_customer_usage(gen_random_uuid(), shop_id, 'booking_started') from booking_test_context;
select save_my_privacy(true,true,false);
select pg_temp.check_booking_test((get_my_privacy()->'preferences'->>'analytics')::boolean, 'Customer can opt in');
create temporary table insight_survey as select next_customer_survey() as value;
select pg_temp.check_booking_test((select value->>'question' = 'discovery' from insight_survey), 'First survey follows fixed order');
select pg_temp.check_booking_test(next_customer_survey() is null, 'Server enforces 30 day cooldown');
select pg_temp.expect_booking_error('select answer_customer_survey((select (value->>''id'')::uuid from insight_survey), ''invalid'')', 'P0001', 'Invalid survey answer rejected');
select answer_customer_survey((value->>'id')::uuid, 'referral') from insight_survey;
select pg_temp.check_booking_test(jsonb_array_length(get_my_privacy()->'responses') = 1, 'Own response visible');
select record_customer_usage(gen_random_uuid(), shop_id, 'booking_started') from booking_test_context;
select pg_temp.expect_booking_error('select get_business_insights(shop_id, now(), now() + interval ''1 day'') from booking_test_context', 'P0001', 'Customers cannot read business insights');
select pg_temp.expect_booking_error('select * from customer_usage_events', '42501', 'Raw analytics inaccessible');
select set_config('request.jwt.claim.sub', customer_b::text, true) from booking_test_context;
select pg_temp.check_booking_test(jsonb_array_length(get_my_privacy()->'responses') = 0, 'Other customer cannot see answers');
select save_my_privacy(true,true,false);
select pg_temp.expect_booking_error('select answer_customer_survey((select (value->>''id'')::uuid from insight_survey), ''referral'')', 'P0001', 'Other customer cannot answer survey');
select set_config('request.jwt.claim.sub', customer_a::text, true) from booking_test_context;
select erase_my_optional_data();
select pg_temp.check_booking_test(jsonb_array_length(get_my_privacy()->'responses') = 0, 'Optional answers erased');
select pg_temp.check_booking_test(not (get_my_privacy()->'preferences'->>'surveys')::boolean, 'Erasure disables surveys');
select save_my_privacy(false,true,false);
select pg_temp.check_booking_test(next_customer_survey() is null, 'Erasure cannot bypass survey cooldown');
reset role;
select pg_temp.check_booking_test((select count(*) = 0 from customer_usage_events where user_id = (select customer_a from booking_test_context)), 'Withdrawal removes usage records');
select pg_temp.check_booking_test((select quoted_price_cents = 4500 from appointment_facts where appointment_id = (select appointment_id from booking_test_context)), 'Booking price captured');
update services set price_cents = 9900 where id = (select service_id from booking_test_context);
select pg_temp.check_booking_test((select quoted_price_cents = 4500 from appointment_facts where appointment_id = (select appointment_id from booking_test_context)), 'Catalog edits preserve historical price');
select pg_temp.check_booking_test((select count(*) > 0 from appointment_history where appointment_id = (select appointment_id from booking_test_context)), 'Operational changes audited');
select set_config('request.jwt.claim.sub', shop_admin::text, true) from booking_test_context;
set local role authenticated;
select pg_temp.check_booking_test((select get_business_insights(shop_id, starts_at - interval '1 day', starts_at + interval '1 day')->>'bookings' is not null from booking_test_context), 'Owner can access own aggregates');
select pg_temp.expect_booking_error('select get_business_insights(other_shop_id, now(), now() + interval ''1 day'') from booking_test_context', 'P0001', 'Owner cannot access another shop');
select pg_temp.expect_booking_error('select get_business_insights(null, now(), now() + interval ''1 day'')', 'P0001', 'Owner cannot access platform aggregates');
select pg_temp.expect_booking_error('select record_attendance(appointment_id, ''no_show'') from booking_test_context', 'P0001', 'No-show cannot be recorded before appointment end');
reset role;
select pg_temp.check_booking_test(not has_function_privilege('anon', 'public.get_my_privacy()', 'EXECUTE'), 'Anonymous access denied');
