-- Run after booking_reliability.sql in a transaction ending with ROLLBACK.
reset role;
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
set local role authenticated;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,5,null,false) from booking_test_context','P0001','Future occurrence rejected');
reset role;
set local session_replication_role=replica;
update appointments set starts_at=now()-interval '2 hours',ends_at=now()-interval '1 hour',status='confirmed' where id=(select appointment_id from booking_test_context);
set local session_replication_role=origin;
select set_config('request.jwt.claim.sub',customer_a::text,true) from booking_test_context;
set local role authenticated;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,5,null,false) from booking_test_context','P0001','Customer cannot register occurrence');
select set_config('request.jwt.claim.sub',outsider::text,true) from booking_test_context;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,5,null,false) from booking_test_context','P0001','Outsider cannot register occurrence');
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,0,null,false) from booking_test_context','P0001','Zero rejected');
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,null,1441,false) from booking_test_context','P0001','Out of range rejected');
select save_appointment_occurrence(appointment_id,5,10,false) from booking_test_context;
select pg_temp.check_booking_test((get_appointment_attendance(appointment_id)->>'customer_delay_minutes')::integer=5,'Delay saved') from booking_test_context;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,null,null,true) from booking_test_context','P0001','No show incompatible with delays');
select save_appointment_occurrence(appointment_id,8,null,false) from booking_test_context;
select pg_temp.check_booking_test((get_appointment_attendance(appointment_id)->>'customer_delay_minutes')::integer=8,'Delay edited') from booking_test_context;
select save_appointment_occurrence(appointment_id,null,null,false) from booking_test_context;
select pg_temp.check_booking_test(get_appointment_attendance(appointment_id)->>'customer_delay_minutes' is null,'Delay removed') from booking_test_context;
reset role;
update appointment_facts set arrived_at=now()-interval '2 hours',started_at=now()-interval '110 minutes' where appointment_id=(select appointment_id from booking_test_context);
update appointments set status='completed' where id=(select appointment_id from booking_test_context);
set local role authenticated;
select save_appointment_occurrence(appointment_id,4,6,false) from booking_test_context;
select pg_temp.check_booking_test(get_appointment_attendance(appointment_id)->>'arrived_at' is not null,'Legacy arrival preserved after completed edit') from booking_test_context;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,null,null,true) from booking_test_context','P0001','Completed no show rejected');
select save_appointment_occurrence(appointment_id,null,null,false) from booking_test_context;
reset role;
set local session_replication_role=replica;
update appointments set status='confirmed' where id=(select appointment_id from booking_test_context);
set local session_replication_role=origin;
set local role authenticated;
select pg_temp.expect_booking_error('select save_appointment_occurrence(appointment_id,null,null,true) from booking_test_context','P0001','Legacy presence blocks no show');
reset role;
update appointment_facts set arrived_at=null,started_at=null where appointment_id=(select appointment_id from booking_test_context);
set local role authenticated;
select pg_temp.expect_booking_error('select get_occurrence_insights(other_shop_id,now()-interval ''1 day'',now()) from booking_test_context','P0001','Cross shop aggregates denied');
select pg_temp.check_booking_test((get_occurrence_insights(shop_id,now()-interval '1 day',now())->>'customer_sample')::integer=0,'Missing delays excluded') from booking_test_context;
select save_appointment_occurrence(appointment_id,null,null,true) from booking_test_context;
select pg_temp.check_booking_test(get_appointment_attendance(appointment_id)->>'no_show_at' is not null,'No show recorded') from booking_test_context;
reset role;
select pg_temp.check_booking_test((select status='cancelled' from appointments where id=(select appointment_id from booking_test_context)),'No show closes appointment');
