-- Run after booking_reliability.sql in the same rollback-only transaction.
reset role;
delete from availability_blocks where barbershop_id=(select shop_id from booking_test_context);
update business_hours set is_open=true where barbershop_id=(select shop_id from booking_test_context);
create temporary table wait_test(id uuid,wait_id uuid);
insert into wait_test values(gen_random_uuid(),null);
grant select on wait_test to authenticated;
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
set local role authenticated;
update barbershop_settings set waiting_enabled=true where barbershop_id=(select shop_id from booking_test_context);
select pg_temp.expect_booking_error('update barbershop_settings set waiting_cutoff_minutes=-1 where barbershop_id=(select shop_id from booking_test_context)','23514','Invalid cutoff rejected');
reset role;
select set_config('request.jwt.claim.sub',customer_a::text,true) from booking_test_context;
set local role authenticated;
insert into appointments(id,barbershop_id,customer_id,service_id,staff_id,starts_at,ends_at)
select w.id,c.shop_id,c.customer_a,c.service_id,c.staff_id,c.starts_at+interval '7 hours',c.starts_at+interval '450 minutes' from booking_test_context c,wait_test w;
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
select withdraw_appointment_confirmation(id) from wait_test;
reset role;
update wait_test set wait_id=(select id from slot_waits where appointment_id=wait_test.id);
select pg_temp.check_booking_test((select count(*)=1 from slot_waits where id=(select wait_id from wait_test)),'Withdrawal creates retention');
select pg_temp.check_booking_test((select claim_until-hold_until=interval '5 minutes' from slot_waits where id=(select wait_id from wait_test)),'Exclusive window is five minutes');
select set_config('request.jwt.claim.sub',customer_b::text,true) from booking_test_context;
set local role authenticated;
select pg_temp.check_booking_test((select jsonb_array_length(get_waiting_state(shop_id)->'waits')=1 from booking_test_context),'Available opportunity visible');
select pg_temp.check_booking_test((select get_waiting_state(shop_id)->'waits'->0->>'appointment_id' is null from booking_test_context),'Original booking identity hidden');
select pg_temp.expect_booking_error('select * from slot_waits','42501','Raw wait records private');
select pg_temp.expect_booking_error('insert into appointments(barbershop_id,customer_id,service_id,staff_id,starts_at,ends_at) select shop_id,customer_b,service_id,staff_id,starts_at+interval ''7 hours'',starts_at+interval ''450 minutes'' from booking_test_context','23P01','Direct booking blocked during retention');
select waiting_action(w.wait_id,'join',c.service_id) from wait_test w,booking_test_context c;
select pg_temp.expect_booking_error('select waiting_action(wait_id,''claim'') from wait_test','P0001','Cannot claim before release');
select pg_temp.expect_booking_error('select waiting_action(wait_id,''restore'') from wait_test','42501','Customer cannot restore original');
select set_config('request.jwt.claim.sub',customer_a::text,true) from booking_test_context;
select pg_temp.check_booking_test((select jsonb_array_length(get_waiting_state(shop_id)->'waits')=0 from booking_test_context),'Opportunity hidden after first interest');
select pg_temp.expect_booking_error('select waiting_action(w.wait_id,''join'',c.service_id) from wait_test w,booking_test_context c','P0001','Second interested customer rejected');
select pg_temp.expect_booking_error('select waiting_action(wait_id,''leave'') from wait_test','42501','Cannot leave another customer wait');
select set_config('request.jwt.claim.sub',outsider::text,true) from booking_test_context;
select pg_temp.expect_booking_error('select get_waiting_state(shop_id) from booking_test_context','42501','Cross shop wait lookup denied');
select pg_temp.expect_booking_error('select waiting_action(w.wait_id,''join'',c.service_id) from wait_test w,booking_test_context c','42501','Cross shop join denied');
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
select waiting_action(wait_id,'restore') from wait_test;
select pg_temp.check_booking_test((select status='confirmed' from appointments where id=(select id from wait_test)),'Restoration confirms original');
select withdraw_appointment_confirmation(id) from wait_test;
reset role;
update wait_test set wait_id=(select id from slot_waits where appointment_id=wait_test.id and state='holding');
select set_config('request.jwt.claim.sub',customer_b::text,true) from booking_test_context;
set local role authenticated;
select waiting_action(w.wait_id,'join',c.service_id) from wait_test w,booking_test_context c;
select waiting_action(wait_id,'leave') from wait_test;
select waiting_action(w.wait_id,'join',c.service_id) from wait_test w,booking_test_context c;
select set_config('request.jwt.claim.sub',customer_a::text,true) from booking_test_context;
select cancel_appointment(id,null) from wait_test;
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
select pg_temp.expect_booking_error('select waiting_action(wait_id,''restore'') from wait_test','P0001','Original cancellation prevents restoration');
reset role;
select pg_temp.check_booking_test((select state='holding' from slot_waits where id=(select wait_id from wait_test)),'Original cancellation preserves hold');
update slot_waits set hold_until=clock_timestamp()-interval '1 second',claim_until=clock_timestamp()+interval '5 minutes' where id=(select wait_id from wait_test);
select process_slot_waits();
select process_slot_waits();
select pg_temp.check_booking_test((select count(*)=1 from waiting_events where wait_id=(select wait_id from wait_test) and kind='exclusive'),'Release notification is durable and deduplicated');
select set_config('request.jwt.claim.sub',customer_b::text,true) from booking_test_context;
set local role authenticated;
select waiting_action(wait_id,'claim') from wait_test;
select pg_temp.expect_booking_error('select waiting_action(wait_id,''claim'') from wait_test','P0001','Duplicate claim rejected');
reset role;
select pg_temp.check_booking_test((select a.status='confirmed' and a.customer_id=c.customer_b from slot_waits w join appointments a on a.id=w.claimed_appointment_id cross join booking_test_context c where w.id=(select wait_id from wait_test)),'Claim creates a separate confirmed booking');
select pg_temp.check_booking_test((select count(*)=0 from loyalty_ledger where appointment_id=(select claimed_appointment_id from slot_waits where id=(select wait_id from wait_test))),'Claim does not award points');
-- Reuse the claimed booking to verify disabling both stages and no-browser expiry.
update wait_test set id=(select claimed_appointment_id from slot_waits where id=wait_test.wait_id);
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
set local role authenticated;
select withdraw_appointment_confirmation(id) from wait_test;
reset role;
update wait_test set wait_id=(select id from slot_waits where appointment_id=wait_test.id and state='holding');
select set_config('request.jwt.claim.sub',customer_a::text,true) from booking_test_context;
set local role authenticated;
select waiting_action(w.wait_id,'join',c.service_id) from wait_test w,booking_test_context c;
select set_config('request.jwt.claim.sub',shop_admin::text,true) from booking_test_context;
update barbershop_settings set waiting_enabled=false where barbershop_id=(select shop_id from booking_test_context);
reset role;
select pg_temp.check_booking_test((select state='disabled' from slot_waits where id=(select wait_id from wait_test)),'Disable immediately closes active wait');
select pg_temp.check_booking_test((select count(*)=1 from waiting_events where wait_id=(select wait_id from wait_test) and kind='disabled'),'Disable notifies interested customer');
select pg_temp.check_booking_test((select count(*)=0 from slot_waits where barbershop_id=(select shop_id from booking_test_context) and state in ('holding','exclusive')),'Disable leaves no active holds');
