/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PoliticaRouteImport } from './routes/politica'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcordoDeDadosRouteImport } from './routes/acordo-de-dados'
import { Route as BarberSlugRouteImport } from './routes/$barberSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopPontosRouteImport } from './routes/shop_.pontos'
import { Route as BShopSlugRouteImport } from './routes/b.$shopSlug'
import { Route as AuthGoogleAppsRouteImport } from './routes/auth_.google-apps'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaRoute = PoliticaRouteImport.update({
  id: '/politica',
  path: '/politica',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordoDeDadosRoute = AcordoDeDadosRouteImport.update({
  id: '/acordo-de-dados',
  path: '/acordo-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberSlugRoute = BarberSlugRouteImport.update({
  id: '/$barberSlug',
  path: '/$barberSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPontosRoute = ShopPontosRouteImport.update({
  id: '/shop_/pontos',
  path: '/shop/pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const BShopSlugRoute = BShopSlugRouteImport.update({
  id: '/b/$shopSlug',
  path: '/b/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleAppsRoute = AuthGoogleAppsRouteImport.update({
  id: '/auth_/google-apps',
  path: '/auth/google-apps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$barberSlug': typeof BarberSlugRoute
  '/acordo-de-dados': typeof AcordoDeDadosRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/cadastrar': typeof CadastrarRoute
  '/demo': typeof DemoRoute
  '/platform': typeof PlatformRoute
  '/politica': typeof PoliticaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/shop': typeof ShopRoute
  '/termos': typeof TermosRoute
  '/auth/google-apps': typeof AuthGoogleAppsRoute
  '/b/$shopSlug': typeof BShopSlugRoute
  '/shop/pontos': typeof ShopPontosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$barberSlug': typeof BarberSlugRoute
  '/acordo-de-dados': typeof AcordoDeDadosRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/cadastrar': typeof CadastrarRoute
  '/demo': typeof DemoRoute
  '/platform': typeof PlatformRoute
  '/politica': typeof PoliticaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/shop': typeof ShopRoute
  '/termos': typeof TermosRoute
  '/auth/google-apps': typeof AuthGoogleAppsRoute
  '/b/$shopSlug': typeof BShopSlugRoute
  '/shop/pontos': typeof ShopPontosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$barberSlug': typeof BarberSlugRoute
  '/acordo-de-dados': typeof AcordoDeDadosRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/cadastrar': typeof CadastrarRoute
  '/demo': typeof DemoRoute
  '/platform': typeof PlatformRoute
  '/politica': typeof PoliticaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/shop': typeof ShopRoute
  '/termos': typeof TermosRoute
  '/auth_/google-apps': typeof AuthGoogleAppsRoute
  '/b/$shopSlug': typeof BShopSlugRoute
  '/shop_/pontos': typeof ShopPontosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$barberSlug'
    | '/acordo-de-dados'
    | '/app'
    | '/auth'
    | '/cadastrar'
    | '/demo'
    | '/platform'
    | '/politica'
    | '/privacidade'
    | '/shop'
    | '/termos'
    | '/auth/google-apps'
    | '/b/$shopSlug'
    | '/shop/pontos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$barberSlug'
    | '/acordo-de-dados'
    | '/app'
    | '/auth'
    | '/cadastrar'
    | '/demo'
    | '/platform'
    | '/politica'
    | '/privacidade'
    | '/shop'
    | '/termos'
    | '/auth/google-apps'
    | '/b/$shopSlug'
    | '/shop/pontos'
  id:
    | '__root__'
    | '/'
    | '/$barberSlug'
    | '/acordo-de-dados'
    | '/app'
    | '/auth'
    | '/cadastrar'
    | '/demo'
    | '/platform'
    | '/politica'
    | '/privacidade'
    | '/shop'
    | '/termos'
    | '/auth_/google-apps'
    | '/b/$shopSlug'
    | '/shop_/pontos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarberSlugRoute: typeof BarberSlugRoute
  AcordoDeDadosRoute: typeof AcordoDeDadosRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CadastrarRoute: typeof CadastrarRoute
  DemoRoute: typeof DemoRoute
  PlatformRoute: typeof PlatformRoute
  PoliticaRoute: typeof PoliticaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ShopRoute: typeof ShopRoute
  TermosRoute: typeof TermosRoute
  AuthGoogleAppsRoute: typeof AuthGoogleAppsRoute
  BShopSlugRoute: typeof BShopSlugRoute
  ShopPontosRoute: typeof ShopPontosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica': {
      id: '/politica'
      path: '/politica'
      fullPath: '/politica'
      preLoaderRoute: typeof PoliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acordo-de-dados': {
      id: '/acordo-de-dados'
      path: '/acordo-de-dados'
      fullPath: '/acordo-de-dados'
      preLoaderRoute: typeof AcordoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$barberSlug': {
      id: '/$barberSlug'
      path: '/$barberSlug'
      fullPath: '/$barberSlug'
      preLoaderRoute: typeof BarberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop_/pontos': {
      id: '/shop_/pontos'
      path: '/shop/pontos'
      fullPath: '/shop/pontos'
      preLoaderRoute: typeof ShopPontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$shopSlug': {
      id: '/b/$shopSlug'
      path: '/b/$shopSlug'
      fullPath: '/b/$shopSlug'
      preLoaderRoute: typeof BShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/google-apps': {
      id: '/auth_/google-apps'
      path: '/auth/google-apps'
      fullPath: '/auth/google-apps'
      preLoaderRoute: typeof AuthGoogleAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarberSlugRoute: BarberSlugRoute,
  AcordoDeDadosRoute: AcordoDeDadosRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CadastrarRoute: CadastrarRoute,
  DemoRoute: DemoRoute,
  PlatformRoute: PlatformRoute,
  PoliticaRoute: PoliticaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ShopRoute: ShopRoute,
  TermosRoute: TermosRoute,
  AuthGoogleAppsRoute: AuthGoogleAppsRoute,
  BShopSlugRoute: BShopSlugRoute,
  ShopPontosRoute: ShopPontosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
